### ISSUE TITLE
Anmerkungen

### ISSUE THREAD

**Issue by fsobanski** [nilshartmann/react-training#8]
- Vielleicht willst du [hier](https://github.com/nilshartmann/react-training/blob/3a249ec310ef57a4c92f7b2a37b63f032e577e41/2019_react_hands_on.html#L43) stattdessen schreiben `cd react-training/blog-example/workspace`. Ist vielleicht ein bisschen eindeutiger, um den ersten Schritt so einfach wie möglich zu machen.
- Welches Verzeichnis meinst du [hier](https://github.com/nilshartmann/react-training/blob/3a249ec310ef57a4c92f7b2a37b63f032e577e41/2019_react_hands_on.html#L118)? Es gibt sowohl einfach nur `react-training/blog-example/workspace` als auch `react-training/code/workspace`. Aber das Verzeichnis `code/blog-example/` gibt es nicht.

**Comment by nilshartmann** [comment]
Danke sehr, habe ich korrigiert!
